In [10]:
import pandas as pd
import numpy as np

In [11]:
crimes_df = pd.read_csv('hate_crime.csv')

In [12]:
crimes_df

,INCIDENT_ID,DATA_YEAR,ORI,PUB_AGENCY_NAME,PUB_AGENCY_UNIT,AGENCY_TYPE_NAME,STATE_ABBR,STATE_NAME,DIVISION_NAME,REGION_NAME,...,OFFENDER_RACE,OFFENDER_ETHNICITY,VICTIM_COUNT,OFFENSE_NAME,TOTAL_INDIVIDUAL_VICTIMS,LOCATION_NAME,BIAS_DESC,VICTIM_TYPES,MULTIPLE_OFFENSE,MULTIPLE_BIAS
0,3015,1991,AR0040200,Rogers,NaN,City,AR,Arkansas,West South Central,South,...,White,NaN,1,Intimidation,1.0,Highway/Road/Alley/Street/Sidewalk,Anti-Black or African American,Individual,S,S
1,3016,1991,AR0290100,Hope,NaN,City,AR,Arkansas,West South Central,South,...,Black or African American,NaN,1,Simple Assault,1.0,Highway/Road/Alley/Street/Sidewalk,Anti-White,Individual,S,S
2,43,1991,AR0350100,Pine Bluff,NaN,City,AR,Arkansas,West South Central,South,...,Black or African American,NaN,1,Aggravated Assault,1.0,Residence/Home,Anti-Black or African American,Individual,S,S
3,44,1991,AR0350100,Pine Bluff,NaN,City,AR,Arkansas,West South Central,South,...,Black or African American,NaN,2,Aggravated Assault;Destruction/Damage/Vandalis...,1.0,Highway/Road/Alley/Street/Sidewalk,Anti-White,Individual,M,S
4,3017,1991,AR0350100,Pine Bluff,NaN,City,AR,Arkansas,West South Central,South,...,Black or African American,NaN,1,Aggravated Assault,1.0,Service/Gas Station,Anti-White,Individual,S,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
219572,1318026,2020,WY0170100,Sheridan,NaN,City,WY,Wyoming,Mountain,West,...,White,Not Hispanic or Latino,2,Intimidation,2.0,Park/Playground,"Anti-Lesbian, Gay, Bisexual, or Transgender (M...",Individual,S,S
219573,1142103,2020,WY0210100,Evanston,NaN,City,WY,Wyoming,Mountain,West,...,Unknown,Unknown,1,Destruction/Damage/Vandalism of Property,0.0,Park/Playground,Anti-White,Government,S,S
219574,1318018,2020,WY0210100,Evanston,NaN,City,WY,Wyoming,Mountain,West,...,Black or African American,Not Hispanic or Latino,1,Aggravated Assault,1.0,Residence/Home,Anti-White,Individual,S,S
219575,1318022,2020,WY0210100,Evanston,NaN,City,WY,Wyoming,Mountain,West,...,White,Not Hispanic or Latino,1,Simple Assault,1.0,Residence/Home,Anti-Female,Individual,S,S
219576,1318023,2020,WY0210100,Evanston,NaN,City,WY,Wyoming,Mountain,West,...,White,Not Hispanic or Latino,1,Theft From Building,1.0,Residence/Home,Anti-Gender Non-Conforming,Individual,S,S

In [13]:
crimes_df.columns

Index(['INCIDENT_ID', 'DATA_YEAR', 'ORI', 'PUB_AGENCY_NAME', 'PUB_AGENCY_UNIT',
       'AGENCY_TYPE_NAME', 'STATE_ABBR', 'STATE_NAME', 'DIVISION_NAME',
       'REGION_NAME', 'POPULATION_GROUP_CODE', 'POPULATION_GROUP_DESC',
       'INCIDENT_DATE', 'ADULT_VICTIM_COUNT', 'JUVENILE_VICTIM_COUNT',
       'TOTAL_OFFENDER_COUNT', 'ADULT_OFFENDER_COUNT',
       'JUVENILE_OFFENDER_COUNT', 'OFFENDER_RACE', 'OFFENDER_ETHNICITY',
       'VICTIM_COUNT', 'OFFENSE_NAME', 'TOTAL_INDIVIDUAL_VICTIMS',
       'LOCATION_NAME', 'BIAS_DESC', 'VICTIM_TYPES', 'MULTIPLE_OFFENSE',
       'MULTIPLE_BIAS'],
      dtype='object')

In [14]:
len(crimes_df)

219577

In [15]:
crimes_df['DATA_YEAR'].unique()

array([1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001,
       2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012,
       2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020])

In [16]:
crimes_df['STATE_ABBR'].unique()

array(['AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'GA', 'IA', 'ID', 'IL',
       'KS', 'MA', 'MD', 'MN', 'MO', 'MS', 'NJ', 'NV', 'NY', 'OH', 'OK',
       'OR', 'PA', 'TN', 'TX', 'VA', 'WA', 'WI', 'AL', 'FL', 'IN', 'KY',
       'LA', 'ME', 'MI', 'NC', 'ND', 'RI', 'SC', 'UT', 'WY', 'AK', 'MT',
       'NM', 'SD', 'VT', 'NH', 'NB', 'WV', 'GM', 'FS', 'HI'], dtype=object)

In [17]:
crimes_df['STATE_NAME'].unique()

array(['Arkansas', 'Arizona', 'California', 'Colorado', 'Connecticut',
       'District of Columbia', 'Delaware', 'Georgia', 'Iowa', 'Idaho',
       'Illinois', 'Kansas', 'Massachusetts', 'Maryland', 'Minnesota',
       'Missouri', 'Mississippi', 'New Jersey', 'Nevada', 'New York',
       'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Tennessee', 'Texas',
       'Virginia', 'Washington', 'Wisconsin', 'Alabama', 'Florida',
       'Indiana', 'Kentucky', 'Louisiana', 'Maine', 'Michigan',
       'North Carolina', 'North Dakota', 'Rhode Island', 'South Carolina',
       'Utah', 'Wyoming', 'Alaska', 'Montana', 'New Mexico',
       'South Dakota', 'Vermont', 'New Hampshire', 'Nebraska',
       'West Virginia', 'Guam', 'Federal', 'Hawaii'], dtype=object)

In [18]:
#take out federal and Guam
crimes_df = crimes_df[crimes_df['STATE_ABBR'] != 'FS']
crimes_df = crimes_df[crimes_df['STATE_ABBR'] != 'GM']

In [19]:
#Check that df only consists of 50 states and DC
len(crimes_df['STATE_ABBR'].unique())

51

In [20]:
crimes_df['BIAS_DESC'].unique()
#Found "Anti-Asian", "Anti-Female"

array(['Anti-Black or African American', 'Anti-White', 'Anti-Jewish',
       'Anti-Arab', 'Anti-Protestant', 'Anti-Other Religion',
       'Anti-Islamic (Muslim)', 'Anti-Gay (Male)', 'Anti-Asian',
       'Anti-Catholic', 'Anti-Heterosexual', 'Anti-Hispanic or Latino',
       'Anti-Other Race/Ethnicity/Ancestry',
       'Anti-Multiple Religions, Group', 'Anti-Multiple Races, Group',
       'Anti-Lesbian (Female)',
       'Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group)',
       'Anti-American Indian or Alaska Native',
       'Anti-Gay (Male);Anti-White',
       'Anti-Black or African American;Anti-Jewish',
       'Anti-Black or African American;Anti-Lesbian (Female)',
       'Anti-Black or African American;Anti-Gay (Male)',
       'Anti-Black or African American;Anti-White',
       'Anti-Atheism/Agnosticism', 'Anti-Gay (Male);Anti-Jewish',
       'Anti-Bisexual', 'Anti-Hispanic or Latino;Anti-White',
       'Anti-Hispanic or Latino;Anti-Multiple Races, Group',
       'Anti-American Indian or Alaska Native;Anti-Hispanic or Latino',
       'Anti-Black or African American;Anti-Gay (Male);Anti-White',
       'Anti-Asian;Anti-Gay (Male)',
       'Anti-Multiple Races, Group;Anti-Other Race/Ethnicity/Ancestry',
       'Anti-Physical Disability',
       'Anti-Lesbian (Female);Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group)',
       'Anti-Mental Disability',
       'Anti-Asian;Anti-Other Race/Ethnicity/Ancestry',
       'Anti-Black or African American;Anti-Hispanic or Latino',
       'Anti-Black or African American;Anti-Other Race/Ethnicity/Ancestry',
       'Anti-Black or African American;Anti-Multiple Races, Group',
       'Anti-Jewish;Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group)',
       'Anti-Lesbian (Female);Anti-White',
       'Anti-Other Race/Ethnicity/Ancestry;Anti-White',
       'Anti-Heterosexual;Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group)',
       'Anti-Multiple Religions, Group;Anti-Other Religion',
       'Anti-Jewish;Anti-White', 'Anti-Arab;Anti-Hispanic or Latino',
       'Anti-Asian;Anti-Black or African American',
       'Anti-American Indian or Alaska Native;Anti-Islamic (Muslim)',
       'Anti-American Indian or Alaska Native;Anti-Asian',
       'Anti-Black or African American;Anti-Protestant',
       'Anti-American Indian or Alaska Native;Anti-Black or African American',
       'Anti-Jewish;Anti-Multiple Races, Group',
       'Anti-Jewish;Anti-Multiple Religions, Group',
       'Anti-Jewish;Anti-Other Race/Ethnicity/Ancestry',
       'Anti-Gay (Male);Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group)',
       'Anti-Hispanic or Latino;Anti-Other Race/Ethnicity/Ancestry',
       'Anti-Gay (Male);Anti-Other Race/Ethnicity/Ancestry',
       'Anti-Multiple Races, Group;Anti-Other Religion',
       'Anti-Gay (Male);Anti-Multiple Races, Group',
       'Anti-Other Religion;Anti-Protestant',
       'Anti-Islamic (Muslim);Anti-Jewish',
       'Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group);Anti-White',
       'Anti-Bisexual;Anti-Heterosexual', 'Anti-Gender Non-Conforming',
       'Anti-Female', 'Anti-Islamic (Muslim);Anti-Other Religion',
       'Anti-Black or African American;Anti-Islamic (Muslim)',
       'Anti-Transgender', 'Anti-Bisexual;Anti-Black or African American',
       'Anti-Gay (Male);Anti-Lesbian (Female)',
       'Anti-Native Hawaiian or Other Pacific Islander',
       'Anti-Gay (Male);Anti-Mental Disability',
       'Anti-Gay (Male);Anti-Islamic (Muslim)', 'Anti-Male',
       'Anti-Multiple Races, Group;Anti-Multiple Religions, Group',
       'Anti-Black or African American;Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group)',
       'Anti-Mental Disability;Anti-Physical Disability',
       'Anti-Other Race/Ethnicity/Ancestry;Anti-Other Religion',
       'Anti-Multiple Religions, Group;Anti-Protestant',
       'Anti-Black or African American;Anti-Jewish;Anti-White',
       "Anti-Jehovah's Witness", 'Anti-Mormon', 'Anti-Buddhist',
       'Anti-Sikh', 'Anti-Other Christian', 'Anti-Hindu',
       'Anti-Asian;Anti-Atheism/Agnosticism',
       'Anti-Eastern Orthodox (Russian, Greek, Other)',
       'Anti-Arab;Anti-Black or African American',
       'Anti-Catholic;Anti-Jewish',
       'Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group);Anti-Physical Disability',
       'Anti-Bisexual;Anti-Gay (Male)', 'Anti-Other Religion;Anti-White',
       'Anti-Asian;Anti-Female',
       'Anti-Jewish;Anti-Lesbian (Female);Anti-White',
       'Anti-Black or African American;Anti-Hispanic or Latino;Anti-Multiple Races, Group;Anti-White',
       'Anti-Islamic (Muslim);Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group)',
       'Anti-Gay (Male);Anti-Transgender',
       'Anti-Hispanic or Latino;Anti-Jewish',
       'Anti-Gay (Male);Anti-Physical Disability',
       'Anti-Lesbian (Female);Anti-Other Religion',
       'Anti-Gay (Male);Anti-Lesbian (Female);Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group)',
       'Anti-Arab;Anti-Black or African American;Anti-Islamic (Muslim)',
       'Anti-Arab;Anti-Hispanic or Latino;Anti-Islamic (Muslim)',
       'Anti-Arab;Anti-Islamic (Muslim)', 'Anti-Female;Anti-Gay (Male)',
       'Anti-Asian;Anti-Hispanic or Latino',
       'Anti-Islamic (Muslim);Anti-Multiple Races, Group',
       'Anti-Arab;Anti-Multiple Races, Group',
       'Anti-Black or African American;Anti-Other Religion',
       'Anti-Multiple Races, Group;Anti-White',
       'Anti-Physical Disability;Anti-White',
       'Anti-Black or African American;Anti-Jewish;Anti-Multiple Races, Group',
       'Anti-Black or African American;Anti-Transgender',
       'Anti-Transgender;Anti-White',
       'Anti-Multiple Religions, Group;Anti-Transgender',
       'Anti-Jewish;Anti-Transgender', 'Anti-Female;Anti-White',
       'Anti-Female;Anti-Mental Disability',
       'Anti-Gay (Male);Anti-Heterosexual',
       'Anti-Catholic;Anti-Protestant',
       'Anti-Mental Disability;Anti-Other Race/Ethnicity/Ancestry',
       'Anti-Black or African American;Anti-Mental Disability',
       'Anti-Male;Anti-Native Hawaiian or Other Pacific Islander',
       'Anti-Arab;Anti-Asian;Anti-Black or African American',
       'Anti-Asian;Anti-Islamic (Muslim)',
       'Anti-Hispanic or Latino;Anti-Male',
       'Anti-Black or African American;Anti-Jewish;Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group)',
       'Anti-Black or African American;Anti-Jewish;Anti-Multiple Races, Group;Anti-Multiple Religions, Group',
       'Anti-Jewish;Anti-Multiple Races, Group;Anti-Multiple Religions, Group',
       'Anti-Hispanic or Latino;Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group)',
       'Anti-Male;Anti-White', 'Anti-Jewish;Anti-Lesbian (Female)',
       'Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group);Anti-Multiple Races, Group',
       'Anti-Female;Anti-Mental Disability;Anti-White',
       'Anti-Male;Anti-Multiple Races, Group;Anti-White',
       'Anti-Asian;Anti-White',
       'Anti-Black or African American;Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group);Anti-Transgender',
       'Anti-Black or African American;Anti-Gay (Male);Anti-Lesbian (Female)',
       "Unknown (offender's motivation not known)",
       'Anti-Gay (Male);Anti-Male',
       'Anti-Black or African American;Anti-Gay (Male);Anti-Jewish',
       'Anti-American Indian or Alaska Native;Anti-White',
       'Anti-Asian;Anti-Multiple Races, Group',
       'Anti-Female;Anti-Hispanic or Latino',
       'Anti-Hispanic or Latino;Anti-Islamic (Muslim)',
       'Anti-Gay (Male);Anti-Hispanic or Latino',
       'Anti-Female;Anti-Lesbian (Female)',
       'Anti-Gender Non-Conforming;Anti-Transgender',
       'Anti-Other Christian;Anti-Other Religion',
       'Anti-Multiple Religions, Group;Anti-Other Christian;Anti-Other Race/Ethnicity/Ancestry;Anti-Other Religion',
       'Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group);Anti-Transgender',
       'Anti-Black or African American;Anti-Physical Disability',
       'Anti-Hispanic or Latino;Anti-Lesbian (Female)',
       'Anti-Lesbian (Female);Anti-Transgender',
       'Anti-American Indian or Alaska Native;Anti-Native Hawaiian or Other Pacific Islander',
       'Anti-Arab;Anti-Islamic (Muslim);Anti-Multiple Religions, Group',
       'Anti-Asian;Anti-Sikh', 'Anti-Asian;Anti-Hindu',
       'Anti-Jewish;Anti-Other Race/Ethnicity/Ancestry;Anti-White',
       'Anti-Arab;Anti-Gay (Male)',
       'Anti-Female;Anti-Multiple Races, Group',
       'Anti-Gender Non-Conforming;Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group);Anti-Multiple Races, Group;Anti-Transgender',
       'Anti-Female;Anti-Other Religion',
       'Anti-Female;Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group)',
       'Anti-Jewish;Anti-Lesbian (Female);Anti-Multiple Races, Group',
       'Anti-Black or African American;Anti-Female;Anti-Lesbian (Female)',
       'Anti-Black or African American;Anti-Hispanic or Latino;Anti-Jewish',
       'Anti-Black or African American;Anti-Jewish;Anti-Other Race/Ethnicity/Ancestry',
       'Anti-Islamic (Muslim);Anti-White',
       "Anti-Jehovah's Witness;Anti-Other Race/Ethnicity/Ancestry",
       'Anti-Gay (Male);Anti-Jewish;Anti-Multiple Races, Group',
       'Anti-Other Race/Ethnicity/Ancestry;Anti-Protestant',
       'Anti-Black or African American;Anti-Female',
       'Anti-Catholic;Anti-Hispanic or Latino',
       'Anti-Hispanic or Latino;Anti-Other Christian',
       'Anti-Hindu;Anti-Other Race/Ethnicity/Ancestry',
       'Anti-Black or African American;Anti-Jewish;Anti-Mental Disability;Anti-Multiple Races, Group',
       'Anti-Islamic (Muslim);Anti-Jewish;Anti-Multiple Races, Group',
       'Anti-Black or African American;Anti-Islamic (Muslim);Anti-Jewish;Anti-Other Race/Ethnicity/Ancestry;Anti-Other Religion',
       'Anti-Jewish;Anti-Other Christian',
       'Anti-Black or African American;Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group);Anti-Multiple Religions, Group',
       'Anti-Black or African American;Anti-Gay (Male);Anti-Jewish;Anti-Other Race/Ethnicity/Ancestry',
       'Anti-Gender Non-Conforming;Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group)',
       'Anti-Arab;Anti-Jewish',
       'Anti-Other Race/Ethnicity/Ancestry;Anti-Sikh',
       'Anti-Jewish;Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group);Anti-Other Race/Ethnicity/Ancestry',
       'Anti-Jewish;Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group);Anti-Multiple Races, Group',
       'Anti-Black or African American;Anti-Gay (Male);Anti-Hispanic or Latino;Anti-Jewish',
       'Anti-Islamic (Muslim);Anti-Other Race/Ethnicity/Ancestry',
       'Anti-Catholic;Anti-Multiple Religions, Group',
       'Anti-Catholic;Anti-Female;Anti-Multiple Races, Group',
       'Anti-Black or African American;Anti-Heterosexual;Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group)',
       'Anti-Black or African American;Anti-Jewish;Anti-Multiple Religions, Group',
       'Anti-Gay (Male);Anti-Jewish;Anti-Other Race/Ethnicity/Ancestry',
       'Anti-Asian;Anti-Male;Anti-White', 'Anti-Asian;Anti-Jewish',
       'Anti-Hispanic or Latino;Anti-Mental Disability',
       'Anti-Gay (Male);Anti-Jewish;Anti-Lesbian (Female);Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group)',
       'Anti-Black or African American;Anti-Male',
       'Anti-Hispanic or Latino;Anti-Physical Disability',
       'Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group);Anti-Multiple Races, Group;Anti-Multiple Religions, Group',
       'Anti-Gay (Male);Anti-Gender Non-Conforming;Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group)',
       'Anti-Black or African American;Anti-Heterosexual;Anti-Jewish',
       'Anti-Jewish;Anti-Mental Disability;Anti-Other Race/Ethnicity/Ancestry;Anti-Physical Disability',
       'Anti-Catholic;Anti-Other Christian;Anti-White',
       'Anti-Gender Non-Conforming;Anti-Jewish;Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group)',
       'Anti-Catholic;Anti-Other Christian',
       'Anti-American Indian or Alaska Native;Anti-Other Race/Ethnicity/Ancestry',
       'Anti-Arab;Anti-Islamic (Muslim);Anti-Jewish',
       'Anti-Arab;Anti-Hispanic or Latino;Anti-Other Race/Ethnicity/Ancestry',
       'Anti-Asian;Anti-Gay (Male);Anti-Jewish',
       'Anti-Bisexual;Anti-Gay (Male);Anti-Transgender',
       'Anti-Female;Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group);Anti-White',
       'Anti-Heterosexual;Anti-Transgender', 'Anti-Arab;Anti-White',
       'Anti-Islamic (Muslim);Anti-Mental Disability',
       'Anti-Black or African American;Anti-Gay (Male);Anti-Hispanic or Latino',
       'Anti-Gay (Male);Anti-Hispanic or Latino;Anti-Male',
       'Anti-Asian;Anti-Black or African American;Anti-Islamic (Muslim)',
       'Anti-Black or African American;Anti-Hispanic or Latino;Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group)',
       'Anti-Black or African American;Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group);Anti-Multiple Races, Group',
       'Anti-Black or African American;Anti-Gay (Male);Anti-Hispanic or Latino;Anti-Multiple Races, Group',
       'Anti-Arab;Anti-Black or African American;Anti-Hispanic or Latino;Anti-Jewish',
       'Anti-Asian;Anti-Black or African American;Anti-Gay (Male)',
       'Anti-Female;Anti-Other Race/Ethnicity/Ancestry',
       'Anti-American Indian or Alaska Native;Anti-Black or African American;Anti-Hispanic or Latino;Anti-Jewish;Anti-Other Race/Ethnicity/Ancestry',
       'Anti-Arab;Anti-Islamic (Muslim);Anti-Male',
       'Anti-Black or African American;Anti-Gay (Male);Anti-Male',
       'Anti-Female;Anti-Gay (Male);Anti-Jewish;Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group);Anti-Multiple Races, Group',
       'Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group);Anti-Mental Disability;Anti-Multiple Races, Group;Anti-Multiple Religions, Group;Anti-Physical Disability',
       'Anti-Jewish;Anti-Mental Disability;Anti-White',
       'Anti-Black or African American;Anti-Gay (Male);Anti-Gender Non-Conforming',
       'Anti-Multiple Religions, Group;Anti-White',
       'Anti-Multiple Religions, Group;Anti-Other Race/Ethnicity/Ancestry',
       'Anti-Black or African American;Anti-Islamic (Muslim);Anti-Other Race/Ethnicity/Ancestry',
       'Anti-Heterosexual;Anti-Islamic (Muslim);Anti-Multiple Races, Group',
       'Anti-Arab;Anti-Sikh',
       'Anti-Black or African American;Anti-Hispanic or Latino;Anti-Islamic (Muslim)',
       'Anti-Hispanic or Latino;Anti-Other Religion',
       'Anti-Black or African American;Anti-Female;Anti-Gay (Male);Anti-Lesbian (Female);Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group)',
       'Anti-Arab;Anti-Asian',
       'Anti-Asian;Anti-Black or African American;Anti-Multiple Races, Group',
       'Anti-Asian;Anti-Black or African American;Anti-Gay (Male);Anti-Multiple Races, Group',
       'Anti-Black or African American;Anti-Multiple Religions, Group',
       'Anti-Asian;Anti-Black or African American;Anti-Female;Anti-Jewish;Anti-Multiple Races, Group',
       'Anti-Black or African American;Anti-Catholic',
       'Anti-Female;Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group);Anti-Multiple Races, Group;Anti-Multiple Religions, Group',
       'Anti-Arab;Anti-Black or African American;Anti-Hispanic or Latino',
       'Anti-Black or African American;Anti-Gay (Male);Anti-Islamic (Muslim);Anti-Jewish;Anti-Lesbian (Female)',
       'Anti-Black or African American;Anti-Multiple Races, Group;Anti-White',
       'Anti-Gay (Male);Anti-Gender Non-Conforming',
       'Anti-Asian;Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group)',
       'Anti-Multiple Races, Group;Anti-Other Christian',
       'Anti-Protestant;Anti-White',
       'Anti-Black or African American;Anti-Gay (Male);Anti-Islamic (Muslim)',
       'Anti-Black or African American;Anti-Native Hawaiian or Other Pacific Islander',
       'Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group);Anti-Other Race/Ethnicity/Ancestry',
       'Anti-Bisexual;Anti-Jewish',
       'Anti-Lesbian (Female);Anti-Other Christian;Anti-White',
       'Anti-Hindu;Anti-Islamic (Muslim);Anti-Other Race/Ethnicity/Ancestry',
       'Anti-Heterosexual;Anti-White',
       'Anti-Black or African American;Anti-Gay (Male);Anti-Transgender',
       'Anti-Female;Anti-Sikh',
       'Anti-Asian;Anti-Black or African American;Anti-Female;Anti-Hispanic or Latino;Anti-Other Race/Ethnicity/Ancestry',
       'Anti-Black or African American;Anti-Other Christian',
       'Anti-Mental Disability;Anti-White',
       "Anti-Gender Non-Conforming;Anti-Jehovah's Witness",
       'Anti-Jewish;Anti-Other Religion',
       'Anti-Gender Non-Conforming;Anti-White',
       'Anti-Asian;Anti-Black or African American;Anti-Hispanic or Latino',
       'Anti-Black or African American;Anti-Gender Non-Conforming',
       'Anti-Bisexual;Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group)',
       'Anti-Black or African American;Anti-Multiple Religions, Group;Anti-Native Hawaiian or Other Pacific Islander',
       'Anti-Asian;Anti-Black or African American;Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group)',
       'Anti-Hispanic or Latino;Anti-Native Hawaiian or Other Pacific Islander'],
      dtype=object)

In [21]:
crimes_df = crimes_df[crimes_df['BIAS_DESC'].str.contains('Anti-Asian')]

In [22]:
len(crimes_df)
#6462 hate crimes against Asians

6462

In [23]:
sum(crimes_df['BIAS_DESC'].str.contains('Anti-Female'))
#5 anti-asian, anti-female crimes

5

In [24]:
crimes_df['VICTIM_TYPES'].unique()

array(['Individual', 'Business;Individual', 'Other', 'Individual;Other',
       'Business', 'Society/Public', 'Government',
       'Individual;Society/Public', 'Religious Organization', 'Unknown',
       'Government;Individual', 'Individual;Religious Organization',
       'Financial Institution', 'Law Enforcement Officer',
       'Individual;Unknown', 'Individual;Law Enforcement Officer'],
      dtype=object)

In [25]:
anti_asian_df = crimes_df.groupby('DATA_YEAR', as_index = False).agg({'INCIDENT_ID': 'count'})

In [26]:
#Anti-Asian crimes per year where victims are an individual, a business/financial institution, a government entity, a religious organization, or society/public as a whole
anti_asian_df

    DATA_YEAR  INCIDENT_ID
0        1991          269
1        1992          222
2        1993          260
3        1994          211
4        1995          355
5        1996          356
6        1997          346
7        1998          297
8        1999          304
9        2000          280
10       2001          280
11       2002          219
12       2003          236
13       2004          224
14       2005          208
15       2006          182
16       2007          190
17       2008          143
18       2009          128
19       2010          152
20       2011          137
21       2012          144
22       2013          134
23       2014          139
24       2015          115
25       2016          115
26       2017          132
27       2018          151
28       2019          199
29       2020          334

**From 2019 to 2020, there was a 68% increase in anti-Asian hate crimes. In the FBI's Hate Crime Statistics Program, victims are an individual, a business/financial institution, a government entity, a religious organization, or society/public as a whole.**

In [27]:
anti_asianfemale_df = crimes_df[crimes_df['BIAS_DESC'].str.contains('Anti-Female')]

In [28]:
anti_asianfemale_df.groupby('DATA_YEAR', as_index = False).agg({'INCIDENT_ID': 'count'})

   DATA_YEAR  INCIDENT_ID
0       2016            1
1       2019            1
2       2020            3

**While we need more data on attacks against Asian females, the data indicates that there was a 200% increase in attacks directed toward this demographic.**

In [29]:
crimes_df

,INCIDENT_ID,DATA_YEAR,ORI,PUB_AGENCY_NAME,PUB_AGENCY_UNIT,AGENCY_TYPE_NAME,STATE_ABBR,STATE_NAME,DIVISION_NAME,REGION_NAME,...,OFFENDER_RACE,OFFENDER_ETHNICITY,VICTIM_COUNT,OFFENSE_NAME,TOTAL_INDIVIDUAL_VICTIMS,LOCATION_NAME,BIAS_DESC,VICTIM_TYPES,MULTIPLE_OFFENSE,MULTIPLE_BIAS
43,33,1991,AZ0072300,Phoenix,NaN,City,AZ,Arizona,Mountain,West,...,White,NaN,1,Intimidation,1.0,Highway/Road/Alley/Street/Sidewalk,Anti-Asian,Individual,S,S
55,3010,1991,AZ0072300,Phoenix,NaN,City,AZ,Arizona,Mountain,West,...,Unknown,NaN,1,Intimidation,1.0,Restaurant,Anti-Asian,Individual,S,S
63,51,1991,CA0300900,Garden Grove,NaN,City,CA,California,Pacific,West,...,White,NaN,2,Aggravated Assault,2.0,Parking/Drop Lot/Garage,Anti-Asian,Individual,S,S
71,77,1991,CO0010100,Aurora,NaN,City,CO,Colorado,Mountain,West,...,White,NaN,1,Aggravated Assault,1.0,Residence/Home,Anti-Asian,Individual,S,S
116,95,1991,CO0031200,Chatfield State Park,NaN,Other State Agency,CO,Colorado,Mountain,West,...,White,NaN,1,Destruction/Damage/Vandalism of Property,1.0,Other/Unknown,Anti-Asian,Individual,S,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
219258,1337705,2020,WASPD0000,Seattle,NaN,City,WA,Washington,Pacific,West,...,Unknown,Unknown,1,Intimidation,1.0,Residence/Home,Anti-Asian,Individual,S,S
219319,1337899,2020,WASPD0000,Seattle,NaN,City,WA,Washington,Pacific,West,...,Unknown,Unknown,1,Intimidation,1.0,Residence/Home,Anti-Asian,Individual,S,S
219342,1331508,2020,WI0130100,Madison,NaN,City,WI,Wisconsin,East North Central,Midwest,...,White,Unknown,2,Simple Assault,2.0,Residence/Home,Anti-Asian,Individual,S,S
219359,1331485,2020,WI0130800,University of Wisconsin:,Madison,University or College,WI,Wisconsin,East North Central,Midwest,...,Unknown,Unknown,1,Destruction/Damage/Vandalism of Property,0.0,School-College/University,Anti-Asian,Business,S,S
219384,1268171,2020,WI0221400,University of Wisconsin:,Platteville,University or College,WI,Wisconsin,East North Central,Midwest,...,Unknown,Unknown,1,Hacking/Computer Invasion,1.0,Cyberspace,Anti-Asian,Individual,S,S

In [30]:
states_2019_df = crimes_df[crimes_df['DATA_YEAR'] == 2019].groupby('STATE_NAME').agg({'INCIDENT_ID': 'count'})
states_2020_df = crimes_df[crimes_df['DATA_YEAR'] == 2020].groupby('STATE_NAME').agg({'INCIDENT_ID': 'count'})

In [31]:
states_2020_df.to_csv('states2020.csv', index = True)
!cp states2020.csv "drive/My Drive/"

cp: cannot create regular file 'drive/My Drive/': No such file or directory

In [32]:
states_2020_2019_df = states_2019_df.merge(states_2020_df, on = "STATE_NAME").rename(columns = {"INCIDENT_ID_x": "Anti-Asian crimes 2019", "INCIDENT_ID_y": "Anti-Asian crimes 2020"})

In [33]:
states_2020_2019_df['Percent increase between 2020 and 2019'] = ((states_2020_2019_df['Anti-Asian crimes 2020'] - states_2020_2019_df['Anti-Asian crimes 2019']) / states_2020_2019_df['Anti-Asian crimes 2019'])*100

In [34]:
states_2020_2019_df.sort_values(by = ['Percent increase between 2020 and 2019'], ascending = False, inplace = True)

In [35]:
states_2020_2019_df

,Anti-Asian crimes 2019,Anti-Asian crimes 2020,Percent increase between 2020 and 2019
STATE_NAME,,,
Minnesota,1,9,800.000000
New York,6,30,400.000000
Nevada,2,8,300.000000
Pennsylvania,2,8,300.000000
Arizona,1,4,300.000000
Illinois,1,3,200.000000
Texas,4,11,175.000000
California,43,91,111.627907
Hawaii,2,4,100.000000
Missouri,1,2,100.000000
New Hampshire,1,2,100.000000
New Jersey,39,67,71.794872
Florida,2,3,50.000000
Virginia,4,5,25.000000
Colorado,6,7,16.666667
District of Columbia,1,1,0.000000
Kentucky,2,2,0.000000
Massachusetts,13,13,0.000000
Arkansas,1,1,0.000000
Washington,29,26,-10.344828
Ohio,6,5,-16.666667
Oregon,7,5,-28.571429
Mississippi,3,2,-33.333333
North Carolina,4,2,-50.000000
Idaho,2,1,-50.000000
Connecticut,2,1,-50.000000
Michigan,6,2,-66.666667

In [36]:
from google.colab import drive
drive.mount('drive')

Mounted at drive

In [37]:
states_2020_2019_df.to_csv('states.csv', index = True)
!cp states.csv "drive/My Drive/"

In [38]:
states_2020_2019_df[states_2020_2019_df['Percent increase between 2020 and 2019'] > 100]

,Anti-Asian crimes 2019,Anti-Asian crimes 2020,Percent increase between 2020 and 2019
STATE_NAME,,,
Minnesota,1,9,800.000000
New York,6,30,400.000000
Nevada,2,8,300.000000
Pennsylvania,2,8,300.000000
Arizona,1,4,300.000000
Illinois,1,3,200.000000
Texas,4,11,175.000000
California,43,91,111.627907

**From 2019 to 2020, Minnesota and New York saw the greatest increase in anti-Asian crimes at 800% and 400%, respectively.**

In [39]:
crimes_df['LOCATION_NAME'].unique()

array(['Highway/Road/Alley/Street/Sidewalk', 'Restaurant',
       'Parking/Drop Lot/Garage', 'Residence/Home', 'Other/Unknown',
       'School/College', 'Grocery/Supermarket', 'Convenience Store',
       'Air/Bus/Train Terminal', 'Service/Gas Station', 'Field/Woods',
       'Liquor Store', 'Specialty Store',
       "Drug Store/Doctor's Office/Hospital", 'Bar/Nightclub',
       'Construction Site', 'Bank/Savings and Loan',
       'Commercial/Office Building', 'Hotel/Motel/Etc.',
       'Church/Synagogue/Temple/Mosque', 'Department/Discount Store',
       'Government/Public Building', 'Lake/Waterway/Beach',
       'Jail/Prison/Penitentiary/Corrections Facility',
       'Residence/Home;School/College', 'Rental Storage Facility',
       'Government/Public Building;Lake/Waterway/Beach',
       'Residence/Home;Restaurant',
       'Parking/Drop Lot/Garage;Residence/Home',
       'Highway/Road/Alley/Street/Sidewalk;Jail/Prison/Penitentiary/Corrections Facility',
       'Highway/Road/Alley/Street/Sidewalk;Residence/Home',
       'School-College/University', 'School-Elementary/Secondary',
       'Park/Playground', 'Shopping Mall',
       'Highway/Road/Alley/Street/Sidewalk;Parking/Drop Lot/Garage',
       'Industrial Site', 'Shelter-Mission/Homeless',
       'Gambling Facility/Casino/Race Track',
       'Convenience Store;Residence/Home', 'Community Center',
       'Auto Dealership New/Used', 'Cyberspace', 'Rest Area'],
      dtype=object)

In [40]:
locations_2019_df = crimes_df[crimes_df['DATA_YEAR'] == 2019].groupby('LOCATION_NAME').agg({'INCIDENT_ID':'count'})
locations_2020_df = crimes_df[crimes_df['DATA_YEAR'] == 2020].groupby('LOCATION_NAME').agg({'INCIDENT_ID':'count'})

In [41]:
locations_2020_2019_df = locations_2019_df.merge(locations_2020_df, on = "LOCATION_NAME").rename(columns = {"INCIDENT_ID_x": "Anti-Asian crime location 2019", "INCIDENT_ID_y": "Anti-Asian crime location 2020"})

In [42]:
locations_2020_2019_df['Percent increase between 2020 and 2019'] = ((locations_2020_2019_df['Anti-Asian crime location 2020'] - locations_2020_2019_df['Anti-Asian crime location 2019']) / locations_2020_2019_df['Anti-Asian crime location 2019'])*100

In [43]:
locations_2020_2019_df.sort_values(by = ['Percent increase between 2020 and 2019'], ascending = False, inplace = True)

In [44]:
locations_2020_2019_df

,Anti-Asian crime location 2019,Anti-Asian crime location 2020,Percent increase between 2020 and 2019
LOCATION_NAME,,,
Convenience Store,2,13,550.000000
Grocery/Supermarket,1,6,500.000000
Other/Unknown,11,48,336.363636
Park/Playground,5,15,200.000000
Residence/Home,35,73,108.571429
Hotel/Motel/Etc.,2,4,100.000000
Service/Gas Station,1,2,100.000000
Drug Store/Doctor's Office/Hospital,4,8,100.000000
Highway/Road/Alley/Street/Sidewalk,43,72,67.441860
School-College/University,6,10,66.666667
Department/Discount Store,3,5,66.666667
Air/Bus/Train Terminal,5,8,60.000000
Church/Synagogue/Temple/Mosque,2,3,50.000000
Shopping Mall,2,3,50.000000
Restaurant,14,17,21.428571
Parking/Drop Lot/Garage,16,18,12.500000
Bank/Savings and Loan,3,3,0.000000
Industrial Site,1,1,0.000000
Field/Woods,1,1,0.000000
Cyberspace,1,1,0.000000
Specialty Store,1,1,0.000000
Commercial/Office Building,3,2,-33.333333
Bar/Nightclub,6,3,-50.000000
School-Elementary/Secondary,15,7,-53.333333
Government/Public Building,7,3,-57.142857
Jail/Prison/Penitentiary/Corrections Facility,4,1,-75.000000

In [45]:
locations_2020_2019_df[locations_2020_2019_df['Percent increase between 2020 and 2019'] > 100]

,Anti-Asian crime location 2019,Anti-Asian crime location 2020,Percent increase between 2020 and 2019
LOCATION_NAME,,,
Convenience Store,2,13,550.000000
Grocery/Supermarket,1,6,500.000000
Other/Unknown,11,48,336.363636
Park/Playground,5,15,200.000000
Residence/Home,35,73,108.571429

**From 2019 to 2020, there was a 550% and 500% increase in anti-Asian attacks at conveience stores and grocery/supermarkets, respectively.**

In [46]:
adult_juv_2019_df = crimes_df[crimes_df['DATA_YEAR'] == 2019].dropna(subset = ['ADULT_VICTIM_COUNT', 'JUVENILE_VICTIM_COUNT'])
adult_juv_2020_df = crimes_df[crimes_df['DATA_YEAR'] == 2020].dropna(subset = ['ADULT_VICTIM_COUNT', 'JUVENILE_VICTIM_COUNT'])

In [47]:
adult_2019 = sum(adult_juv_2019_df['ADULT_VICTIM_COUNT'])
adult_2020 = sum(adult_juv_2020_df['ADULT_VICTIM_COUNT'])

In [48]:
print("Number of Asian adult victims (18 or older) in 2019: ", adult_2019)
print("Number of Asian adult victims (18 or older) in 2020: ", adult_2020)
print("Percent increase in Asian adult victims: ", ((adult_2020 - adult_2019)/adult_2019)*100)

Number of Asian adult victims (18 or older) in 2019:  170.0
Number of Asian adult victims (18 or older) in 2020:  237.0
Percent increase in Asian adult victims:  39.411764705882355

In [49]:
juv_2019 = sum(adult_juv_2019_df['JUVENILE_VICTIM_COUNT'])
juv_2020 = sum(adult_juv_2020_df['JUVENILE_VICTIM_COUNT'])

In [50]:
print("Number of Asian juvenile victims (under 18) in 2019: ", juv_2019)
print("Number of Asian juvenile victims (under 18) in 2020: ", juv_2020)
print("Percent increase in Asian juvenile (under 18) victims: ", ((juv_2020 - juv_2019)/juv_2019)*100)

Number of Asian juvenile victims (under 18) in 2019:  10.0
Number of Asian juvenile victims (under 18) in 2020:  12.0
Percent increase in Asian juvenile (under 18) victims:  20.0

**From 2019 to 2020, hate crimes targeting Asian adults (18 or older) jumped nearly 40% while those targeting Asian juveniles (under 18) increased 20%.**